In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

2022 Data

In [2]:
# 2022 data
# URL of the page to scrape
url = "https://www.espn.com/golf/stats/player/_/season/2022/"

# Make a GET request to the URL and store the response
response = requests.get(url)

# Parse the HTML content of the page using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Find the table containing the player data
table = soup.find('table', class_='Table Table--align-right')

# Get the table headers
headers = [th.text.strip() for th in table.find_all('th')]

# Initialize a list to store the player data
player_data = []

# Loop through each row in the table (skipping the header row)
for tr in table.find_all('tr')[1:]:
    # Get the data for each column in the row
    tds = tr.find_all('td')
    # Initialize a dictionary to store the player's data
    player = {}
    # Loop through each column and add the data to the dictionary
    for i in range(len(headers)):
        player[headers[i]] = tds[i].text.strip()
    # Add the player's data to the list
    player_data.append(player)
    # Stop the loop after 250 players have been scraped
    if len(player_data) == 250:
        break

# Print the data for the first player as an example
print(player_data[0])

{'EARNINGS': '$14,046,910', 'CUP': '-20', 'EVNTS': '25', 'RNDS': '84', 'CUTS': '20', 'TOP10': '11', 'WINS': '4', 'SCORE': '68.9', 'DDIS': '311.6', 'DACC': '60.0', 'GIR': '72.3', 'PUTTS': '1.720', 'SAND': '49.5', 'BIRDS': '4.595'}

In [3]:
df22_1 = pd.DataFrame(player_data)
df22_1

,EARNINGS,CUP,EVNTS,RNDS,CUTS,TOP10,WINS,SCORE,DDIS,DACC,GIR,PUTTS,SAND,BIRDS
0,"$14,046,910",-20,25,84,20,11,4,68.9,311.6,60.0,72.3,1.720,49.5,4.595
1,"$10,107,897",-9,18,62,14,7,3,68.9,299.7,57.5,68.0,1.679,52.2,4.629
2,"$9,405,082",3680,24,76,17,9,1,69.6,314.7,55.4,70.9,1.734,49.0,4.316
3,"$9,369,605",-16,20,68,17,12,2,69.0,308.0,60.6,69.3,1.732,57.7,4.441
4,"$8,654,566",-21,16,60,14,10,3,68.9,321.3,58.1,69.9,1.739,61.6,4.533
5,"$7,427,299",-18,21,72,18,7,3,68.9,308.5,62.2,70.5,1.725,64.9,4.319
6,"$7,073,986",-7,24,80,17,8,3,69.4,309.6,55.4,68.7,1.721,49.6,4.325
7,"$7,012,672",-11,20,70,17,10,1,69.5,303.8,63.4,66.8,1.787,63.9,3.686
8,"$6,829,576",-17,21,76,19,10,1,68.8,314.3,54.8,68.3,1.718,62.7,4.579
9,"$6,520,598",-10,25,82,18,7,0,69.6,319.3,58.7,64.9,1.728,48.2,4.415
10,"$6,117,886",-15,25,86,20,7,2,69.2,308.0,58.0,71.3,1.752,51.1,4.221
11,"$5,776,298",-13,21,72,17,6,2,69.5,304.7,59.4,68.3,1.745,54.9,4.181
12,"$5,567,974",-20,26,88,21,9,1,69.2,303.7,65.5,70.8,1.762,56.9,3.989
13,"$5,289,842",-17,24,82,20,5,2,69.9,306.3,60.6,66.0,1.747,51.6,3.939
14,"$5,248,220",-11,19,70,18,8,1,69.6,318.9,62.5,71.6,1.768,40.8,4.171
15,"$5,076,060",-13,24,80,19,5,1,69.5,309.1,56.7,67.9,1.729,55.2,4.150
16,"$5,018,444",-12,22,74,17,6,1,69.7,308.4,56.0,67.4,1.748,51.4,4.068
17,"$4,940,600",-8,22,70,16,5,1,69.8,297.3,65.1,68.2,1.768,56.3,3.800
18,"$4,868,461",-11,21,70,17,5,1,69.7,308.4,61.9,67.0,1.731,45.5,4.371
19,"$4,837,271",-8,19,60,14,8,0,69.6,301.8,65.3,68.6,1.746,47.2,4.033
20,"$4,722,434",-16,33,98,19,5,1,70.8,303.0,59.9,66.6,1.784,50.0,3.561
21,"$4,310,046",-14,32,96,19,6,1,69.9,298.1,61.6,66.3,1.757,52.0,3.917
22,"$3,933,593",3,31,96,17,7,0,69.9,306.0,54.8,65.4,1.739,55.1,3.948
23,"$3,876,590",-3,25,87,20,4,0,69.7,302.7,66.8,71.9,1.782,45.6,3.862
24,"$3,757,424",1095,24,66,12,5,0,70.2,290.4,65.5,67.2,1.752,49.5,3.833
25,"$3,718,990",1302,22,71,16,4,1,69.5,304.4,61.9,69.3,1.733,58.9,4.099
26,"$3,623,137",946,25,80,18,6,0,70.2,307.5,59.8,66.2,1.754,47.7,3.788
27,"$3,616,679",1222,18,58,14,4,0,69.7,306.9,61.4,67.9,1.767,67.1,3.690
28,"$3,454,521",-12,24,86,19,4,0,69.4,308.3,59.2,69.1,1.748,43.0,4.070
29,"$3,347,180",-1,28,98,21,2,1,70.2,302.5,62.2,65.8,1.755,53.4,3.704
30,"$3,292,443",-11,30,88,15,4,1,69.8,298.2,59.4,66.7,1.771,53.3,3.716
31,"$3,226,839",-8,27,91,21,6,0,69.9,292.2,66.6,67.1,1.776,61.9,3.516
32,"$3,190,793",1150,29,94,19,6,0,69.9,307.6,61.9,67.0,1.727,47.8,4.149
33,"$3,124,668",1,32,113,26,5,0,70.0,304.3,54.0,66.5,1.758,45.2,3.832
34,"$3,100,241",1006,26,78,16,5,0,69.7,301.0,61.8,68.7,1.753,52.8,3.949
35,"$3,084,598",642,24,72,12,3,0,70.6,298.2,61.9,64.9,1.767,50.0,3.486
36,"$3,068,341",1063,26,86,20,6,0,69.5,311.8,61.8,67.6,1.777,54.6,4.058
37,"$3,050,519",974,29,92,19,5,0,70.3,301.9,58.6,67.5,1.765,41.4,3.761
38,"$2,951,152",1177,29,95,19,3,1,70.3,294.7,64.1,67.0,1.752,44.1,3.811
39,"$2,913,198",-4,20,72,18,5,0,70.1,312.4,55.3,67.7,1.742,52.7,4.014
40,"$2,882,771",1111,29,100,22,5,0,69.8,291.6,64.5,65.3,1.744,57.7,3.620
41,"$2,874,008",766,17,56,14,5,0,69.8,301.5,59.4,65.7,1.754,62.2,3.768
42,"$2,849,792",972,19,64,16,3,0,70.2,305.7,54.6,64.1,1.728,58.9,3.875
43,"$2,837,505",1002,22,78,19,4,0,69.5,298.7,67.5,70.9,1.738,39.1,4.205
44,"$2,824,580",1154,11,0,10,3,1,0.0,0.0,0.0,0.0,0.000,0.0,0.000
45,"$2,797,925",962,27,89,18,3,0,69.9,303.9,60.4,69.6,1.765,47.1,3.753
46,"$2,734,720",957,28,80,15,3,1,70.5,314.8,55.1,69.7,1.807,47.6,3.663
47,"$2,689,754",1111,27,88,22,4,0,69.8,307.4,57.9,66.8,1.721,48.6,4.102
48,"$2,574,396",777,26,90,20,5,0,70.1,297.2,63.7,67.8,1.763,59.2,3.822
49,"$2,558,440",1004,20,54,10,2,1,71.3,307.3,50.8,57.8,1.730,63.7,3.741

In [4]:
# The URL of the page we want to scrape
url = "https://www.espn.com/golf/stats/player/_/season/2022/table/general/sort/amount/dir/desc/"

# Send an HTTP request to the URL
response = requests.get(url)

# Parse the HTML content of the page using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Find the table containing the player data
table = soup.find('table')

# Extract the table headers
headers = []
for th in table.find_all('th'):
    headers.append(th.text.strip())

# Extract the player data
players = []
for tr in table.find_all('tr')[1:]:
    player_data = []
    for td in tr.find_all('td'):
        player_data.append(td.text.strip())
    players.append(player_data)

In [5]:
df22_2 = pd.DataFrame(players)

In [6]:
df22_2.columns = ['Rank', 'Name', 'Age']

In [7]:
data_2022 = df22_2.join(df22_1)
data_2022

,Rank,Name,Age,EARNINGS,CUP,EVNTS,RNDS,CUTS,TOP10,WINS,SCORE,DDIS,DACC,GIR,PUTTS,SAND,BIRDS
0,1,Scottie Scheffler,26,"$14,046,910",-20,25,84,20,11,4,68.9,311.6,60.0,72.3,1.720,49.5,4.595
1,2,Cameron Smith,29,"$10,107,897",-9,18,62,14,7,3,68.9,299.7,57.5,68.0,1.679,52.2,4.629
2,3,Will Zalatoris,26,"$9,405,082",3680,24,76,17,9,1,69.6,314.7,55.4,70.9,1.734,49.0,4.316
3,4,Patrick Cantlay,30,"$9,369,605",-16,20,68,17,12,2,69.0,308.0,60.6,69.3,1.732,57.7,4.441
4,5,Rory McIlroy,33,"$8,654,566",-21,16,60,14,10,3,68.9,321.3,58.1,69.9,1.739,61.6,4.533
5,6,Xander Schauffele,29,"$7,427,299",-18,21,72,18,7,3,68.9,308.5,62.2,70.5,1.725,64.9,4.319
6,7,Sam Burns,26,"$7,073,986",-7,24,80,17,8,3,69.4,309.6,55.4,68.7,1.721,49.6,4.325
7,8,Matt Fitzpatrick,28,"$7,012,672",-11,20,70,17,10,1,69.5,303.8,63.4,66.8,1.787,63.9,3.686
8,9,Justin Thomas,29,"$6,829,576",-17,21,76,19,10,1,68.8,314.3,54.8,68.3,1.718,62.7,4.579
9,10,Cameron Young,25,"$6,520,598",-10,25,82,18,7,0,69.6,319.3,58.7,64.9,1.728,48.2,4.415
10,11,Tony Finau,33,"$6,117,886",-15,25,86,20,7,2,69.2,308.0,58.0,71.3,1.752,51.1,4.221
11,12,Hideki Matsuyama,31,"$5,776,298",-13,21,72,17,6,2,69.5,304.7,59.4,68.3,1.745,54.9,4.181
12,13,Sungjae Im,24,"$5,567,974",-20,26,88,21,9,1,69.2,303.7,65.5,70.8,1.762,56.9,3.989
13,14,Max Homa,32,"$5,289,842",-17,24,82,20,5,2,69.9,306.3,60.6,66.0,1.747,51.6,3.939
14,15,Jon Rahm,28,"$5,248,220",-11,19,70,18,8,1,69.6,318.9,62.5,71.6,1.768,40.8,4.171
15,16,Joaquin Niemann,24,"$5,076,060",-13,24,80,19,5,1,69.5,309.1,56.7,67.9,1.729,55.2,4.150
16,17,Jordan Spieth,29,"$5,018,444",-12,22,74,17,6,1,69.7,308.4,56.0,67.4,1.748,51.4,4.068
17,18,Billy Horschel,36,"$4,940,600",-8,22,70,16,5,1,69.8,297.3,65.1,68.2,1.768,56.3,3.800
18,19,Viktor Hovland,25,"$4,868,461",-11,21,70,17,5,1,69.7,308.4,61.9,67.0,1.731,45.5,4.371
19,20,Collin Morikawa,26,"$4,837,271",-8,19,60,14,8,0,69.6,301.8,65.3,68.6,1.746,47.2,4.033
20,21,Sepp Straka,29,"$4,722,434",-16,33,98,19,5,1,70.8,303.0,59.9,66.6,1.784,50.0,3.561
21,22,Tom Hoge,33,"$4,310,046",-14,32,96,19,6,1,69.9,298.1,61.6,66.3,1.757,52.0,3.917
22,23,Scott Stallings,37,"$3,933,593",3,31,96,17,7,0,69.9,306.0,54.8,65.4,1.739,55.1,3.948
23,24,Corey Conners,31,"$3,876,590",-3,25,87,20,4,0,69.7,302.7,66.8,71.9,1.782,45.6,3.862
24,25,Kevin Kisner,39,"$3,757,424",1095,24,66,12,5,0,70.2,290.4,65.5,67.2,1.752,49.5,3.833
25,26,Talor Gooch,31,"$3,718,990",1302,22,71,16,4,1,69.5,304.4,61.9,69.3,1.733,58.9,4.099
26,27,Keegan Bradley,36,"$3,623,137",946,25,80,18,6,0,70.2,307.5,59.8,66.2,1.754,47.7,3.788
27,28,Shane Lowry,35,"$3,616,679",1222,18,58,14,4,0,69.7,306.9,61.4,67.9,1.767,67.1,3.690
28,29,Aaron Wise,26,"$3,454,521",-12,24,86,19,4,0,69.4,308.3,59.2,69.1,1.748,43.0,4.070
29,30,K.H. Lee,31,"$3,347,180",-1,28,98,21,2,1,70.2,302.5,62.2,65.8,1.755,53.4,3.704
30,31,J.T. Poston,29,"$3,292,443",-11,30,88,15,4,1,69.8,298.2,59.4,66.7,1.771,53.3,3.716
31,32,Brian Harman,36,"$3,226,839",-8,27,91,21,6,0,69.9,292.2,66.6,67.1,1.776,61.9,3.516
32,33,Davis Riley,26,"$3,190,793",1150,29,94,19,6,0,69.9,307.6,61.9,67.0,1.727,47.8,4.149
33,34,Sahith Theegala,25,"$3,124,668",1,32,113,26,5,0,70.0,304.3,54.0,66.5,1.758,45.2,3.832
34,35,Seamus Power,36,"$3,100,241",1006,26,78,16,5,0,69.7,301.0,61.8,68.7,1.753,52.8,3.949
35,36,Anirban Lahiri,35,"$3,084,598",642,24,72,12,3,0,70.6,298.2,61.9,64.9,1.767,50.0,3.486
36,37,Keith Mitchell,31,"$3,068,341",1063,26,86,20,6,0,69.5,311.8,61.8,67.6,1.777,54.6,4.058
37,38,Cameron Tringale,35,"$3,050,519",974,29,92,19,5,0,70.3,301.9,58.6,67.5,1.765,41.4,3.761
38,39,J.J. Spaun,32,"$2,951,152",1177,29,95,19,3,1,70.3,294.7,64.1,67.0,1.752,44.1,3.811
39,40,Adam Scott,42,"$2,913,198",-4,20,72,18,5,0,70.1,312.4,55.3,67.7,1.742,52.7,4.014
40,41,Denny McCarthy,30,"$2,882,771",1111,29,100,22,5,0,69.8,291.6,64.5,65.3,1.744,57.7,3.620
41,42,Tommy Fleetwood,32,"$2,874,008",766,17,56,14,5,0,69.8,301.5,59.4,65.7,1.754,62.2,3.768
42,43,Tyrrell Hatton,31,"$2,849,792",972,19,64,16,3,0,70.2,305.7,54.6,64.1,1.728,58.9,3.875
43,44,Russell Henley,33,"$2,837,505",1002,22,78,19,4,0,69.5,298.7,67.5,70.9,1.738,39.1,4.205
44,45,Tom Kim,20,"$2,824,580",1154,11,0,10,3,1,0.0,0.0,0.0,0.0,0.000,0.0,0.000
45,46,Mito Pereira,27,"$2,797,925",962,27,89,18,3,0,69.9,303.9,60.4,69.6,1.765,47.1,3.753
46,47,Luke List,38,"$2,734,720",957,28,80,15,3,1,70.5,314.8,55.1,69.7,1.807,47.6,3.663
47,48,Maverick McNealy,27,"$2,689,754",1111,27,88,22,4,0,69.8,307.4,57.9,66.8,1.721,48.6,4.102
48,49,Adam Hadwin,35,"$2,574,396",777,26,90,20,5,0,70.1,297.2,63.7,67.8,1.763,59.2,3.822
49,50,Lucas Herbert,27,"$2,558,440",1004,20,54,10,2,1,71.3,307.3,50.8,57.8,1.730,63.7,3.741

2021 Data

In [8]:
# URL of the page to scrape
url = "https://www.espn.com/golf/stats/player/_/season/2021/"

# Make a GET request to the URL and store the response
response = requests.get(url)

# Parse the HTML content of the page using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Find the table containing the player data
table = soup.find('table', class_='Table Table--align-right')

# Get the table headers
headers = [th.text.strip() for th in table.find_all('th')]

# Initialize a list to store the player data
player_data = []

# Loop through each row in the table (skipping the header row)
for tr in table.find_all('tr')[1:]:
    # Get the data for each column in the row
    tds = tr.find_all('td')
    # Initialize a dictionary to store the player's data
    player = {}
    # Loop through each column and add the data to the dictionary
    for i in range(len(headers)):
        player[headers[i]] = tds[i].text.strip()
    # Add the player's data to the list
    player_data.append(player)
    # Stop the loop after 250 players have been scraped
    if len(player_data) == 250:
        break

# Print the data for the first player as an example
print(player_data[0])

df21_1 = pd.DataFrame(player_data)
df21_1

# The URL of the page we want to scrape
url = "https://www.espn.com/golf/stats/player/_/season/2021/table/general/sort/amount/dir/desc/"

# Send an HTTP request to the URL
response = requests.get(url)

# Parse the HTML content of the page using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Find the table containing the player data
table = soup.find('table')

# Extract the table headers
headers = []
for th in table.find_all('th'):
    headers.append(th.text.strip())

# Extract the player data
players = []
for tr in table.find_all('tr')[1:]:
    player_data = []
    for td in tr.find_all('td'):
        player_data.append(td.text.strip())
    players.append(player_data)

df21_2 = pd.DataFrame(players)

df21_2.columns = ['Rank', 'Name', 'Age']

data_2021 = df21_2.join(df21_1)
data_2021

{'EARNINGS': '$7,705,933', 'CUP': '-20', 'EVNTS': '22', 'RNDS': '77', 'CUTS': '21', 'TOP10': '15', 'WINS': '1', 'SCORE': '69.0', 'DDIS': '309.0', 'DACC': '63.7', 'GIR': '71.9', 'PUTTS': '1.733', 'SAND': '55.6', 'BIRDS': '4.506'}

,Rank,Name,Age,EARNINGS,CUP,EVNTS,RNDS,CUTS,TOP10,WINS,SCORE,DDIS,DACC,GIR,PUTTS,SAND,BIRDS
0,1,Jon Rahm,28,"$7,705,933",-20,22,77,21,15,1,69.0,309.0,63.7,71.9,1.733,55.6,4.506
1,2,Patrick Cantlay,30,"$7,638,805",-21,24,78,20,7,4,69.4,302.8,60.7,70.2,1.746,59.4,4.295
2,3,Bryson DeChambeau,29,"$7,426,415",-13,22,80,20,9,2,69.6,323.7,54.2,67.2,1.740,49.1,4.500
3,4,Collin Morikawa,26,"$7,059,908",2188,23,78,20,8,2,69.7,295.2,69.6,70.8,1.730,53.9,4.231
4,5,Justin Thomas,29,"$6,537,153",-15,23,84,21,7,1,69.5,303.9,55.7,67.8,1.711,56.1,4.310
5,6,Jordan Spieth,29,"$6,470,482",-4,25,88,21,9,1,69.9,299.5,53.9,64.6,1.708,55.9,4.295
6,7,Louis Oosthuizen,40,"$6,306,679",-7,21,74,20,8,0,69.7,297.8,63.5,67.6,1.747,59.1,3.865
7,8,Harris English,33,"$6,200,481",-6,26,92,22,8,2,69.6,299.4,64.3,65.8,1.718,52.9,4.261
8,9,Cameron Smith,29,"$5,851,867",-7,24,82,21,8,1,69.5,297.9,59.2,65.7,1.689,63.2,4.476
9,10,Abraham Ancer,32,"$5,816,565",-10,27,98,24,9,1,69.5,290.4,71.1,69.3,1.732,50.8,4.204
10,11,Tony Finau,33,"$5,740,097",-8,27,90,22,8,1,69.8,305.5,56.3,67.1,1.722,55.3,4.156
11,12,Xander Schauffele,29,"$5,240,653",-14,22,76,20,8,0,69.7,307.6,58.8,68.6,1.728,64.7,4.276
12,13,Brooks Koepka,32,"$5,204,136",1793,20,66,13,8,1,69.7,310.7,56.6,68.0,1.731,65.4,4.212
13,14,Sam Burns,26,"$5,160,030",-6,26,84,19,8,1,69.6,305.3,58.9,67.8,1.710,51.8,4.429
14,15,Jason Kokrak,37,"$5,118,629",-8,27,88,21,5,2,70.0,307.9,60.2,69.2,1.745,52.2,4.284
15,16,Viktor Hovland,25,"$5,048,772",-14,24,83,22,7,1,69.8,302.2,63.9,68.6,1.743,51.0,4.398
16,17,Dustin Johnson,38,"$5,001,136",-11,21,72,17,9,1,69.6,312.9,57.9,66.7,1.720,55.6,4.250
17,18,Hideki Matsuyama,31,"$4,963,594",1681,27,93,22,3,1,70.2,299.9,62.2,67.0,1.745,48.5,4.065
18,19,Scottie Scheffler,26,"$4,505,589",-3,29,98,24,8,0,69.8,305.0,63.5,68.1,1.719,48.0,4.388
19,20,Rory McIlroy,33,"$4,391,809",-7,21,74,18,7,1,70.1,319.3,57.4,65.8,1.727,53.0,4.514
20,21,Daniel Berger,29,"$4,258,579",-8,23,84,21,8,1,69.3,296.7,65.5,70.5,1.741,54.9,4.226
21,22,Sungjae Im,24,"$4,157,182",-4,35,122,30,5,0,69.8,297.1,69.1,69.1,1.746,51.5,4.082
22,23,Billy Horschel,36,"$4,030,906",-10,25,86,22,6,1,70.5,294.7,65.7,66.5,1.757,51.9,3.686
23,24,Patrick Reed,32,"$4,019,044",-2,23,78,18,6,1,70.1,291.4,63.2,62.1,1.710,61.7,4.000
24,25,Corey Conners,31,"$4,007,567",-3,29,104,25,8,0,69.9,295.4,70.2,69.9,1.746,46.7,3.990
25,26,Joaquin Niemann,24,"$3,936,912",4,27,102,26,5,0,69.7,310.6,59.2,68.6,1.740,51.0,4.137
26,27,Kevin Na,39,"$3,625,982",-16,26,87,20,5,1,69.9,288.5,66.6,64.1,1.739,59.6,4.000
27,28,Stewart Cink,49,"$3,596,319",1656,26,90,19,3,2,70.1,306.6,56.4,69.4,1.760,56.9,3.933
28,29,Will Zalatoris,26,"$3,487,352",0,25,87,21,8,0,69.9,307.4,56.4,69.5,1.777,48.1,3.816
29,30,Max Homa,32,"$3,448,578",1269,28,86,19,5,1,70.6,300.8,58.4,63.9,1.728,52.4,3.930
30,31,Lee Westwood,49,"$3,435,368",1070,19,62,14,2,0,71.2,294.1,62.9,64.8,1.775,45.9,3.484
31,32,Si Woo Kim,27,"$3,245,928",1293,31,94,20,5,1,70.4,296.3,62.7,65.8,1.755,46.5,3.894
32,33,Brian Harman,36,"$3,221,821",1168,28,100,24,5,0,69.8,291.7,66.9,64.3,1.729,59.1,3.910
33,34,Paul Casey,45,"$3,129,666",1005,20,72,18,7,0,70.1,303.9,62.2,68.8,1.771,47.2,3.903
34,35,Marc Leishman,39,"$3,107,047",1167,24,76,18,4,1,70.9,293.8,58.5,65.7,1.771,60.0,3.553
35,36,K.H. Lee,31,"$3,085,133",1339,33,106,22,3,1,70.7,298.4,63.1,64.3,1.756,54.0,3.642
36,37,Charley Hoffman,46,"$3,049,763",1338,29,99,24,5,0,70.0,306.5,57.1,67.8,1.736,47.3,4.202
37,38,Sergio Garcia,43,"$2,998,555",-7,24,74,15,4,1,69.9,309.4,61.2,70.0,1.773,49.6,3.959
38,39,Kevin Kisner,39,"$2,952,177",1214,26,78,17,4,1,70.7,289.1,67.6,65.0,1.747,48.7,3.718
39,40,Webb Simpson,37,"$2,783,012",1195,21,74,18,6,0,69.2,292.5,67.1,69.4,1.734,61.7,4.338
40,41,Cam Davis,28,"$2,746,956",1237,26,94,21,3,1,70.3,309.0,56.1,65.3,1.738,49.0,4.170
41,42,Phil Mickelson,52,"$2,707,199",805,23,74,14,1,1,71.9,301.8,54.5,63.0,1.787,47.7,3.716
42,43,Carlos Ortiz,31,"$2,682,104",1090,28,92,20,3,1,70.2,303.0,60.4,67.0,1.739,43.4,3.891
43,44,Shane Lowry,35,"$2,636,597",1103,21,76,19,4,0,70.6,299.6,59.9,68.3,1.766,48.0,3.908
44,45,Lucas Glover,43,"$2,577,704",1102,30,96,20,4,1,70.6,294.9,64.1,66.7,1.766,51.8,3.833
45,46,Keegan Bradley,36,"$2,572,089",1206,27,86,18,4,0,70.2,300.2,65.0,70.0,1.783,50.0,3.767
46,47,Russell Henley,33,"$2,545,330",978,25,84,19,5,0,69.6,289.8,67.1,69.4,1.764,59.3,3.726
47,48,Matthew Wolff,23,"$2,507,324",772,20,55,13,2,0,70.9,315.9,51.0,64.9,1.754,46.6,3.836
48,49,Matt Jones,42,"$2,496,677",1091,30,102,23,3,1,70.4,304.0,55.6,65.7,1.759,52.8,3.676
49,50,Cameron Tringale,35,"$2,428,609",1165,27,92,21,4,0,69.8,297.5,61.2,67.6,1.729,57.6,4.109

2020 Data

In [9]:
url = "https://www.espn.com/golf/stats/player/_/season/2020/"

# Make a GET request to the URL and store the response
response = requests.get(url)

# Parse the HTML content of the page using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Find the table containing the player data
table = soup.find('table', class_='Table Table--align-right')

# Get the table headers
headers = [th.text.strip() for th in table.find_all('th')]

# Initialize a list to store the player data
player_data = []

# Loop through each row in the table (skipping the header row)
for tr in table.find_all('tr')[1:]:
    # Get the data for each column in the row
    tds = tr.find_all('td')
    # Initialize a dictionary to store the player's data
    player = {}
    # Loop through each column and add the data to the dictionary
    for i in range(len(headers)):
        player[headers[i]] = tds[i].text.strip()
    # Add the player's data to the list
    player_data.append(player)
    # Stop the loop after 250 players have been scraped
    if len(player_data) == 250:
        break

# Print the data for the first player as an example
print(player_data[0])

df20_1 = pd.DataFrame(player_data)
df20_1

# The URL of the page we want to scrape
url = "https://www.espn.com/golf/stats/player/_/season/2020/table/general/sort/amount/dir/desc/"

# Send an HTTP request to the URL
response = requests.get(url)

# Parse the HTML content of the page using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Find the table containing the player data
table = soup.find('table')

# Extract the table headers
headers = []
for th in table.find_all('th'):
    headers.append(th.text.strip())

# Extract the player data
players = []
for tr in table.find_all('tr')[1:]:
    player_data = []
    for td in tr.find_all('td'):
        player_data.append(td.text.strip())
    players.append(player_data)

df20_2 = pd.DataFrame(players)

df20_2.columns = ['Rank', 'Name', 'Age']

data_2020 = df20_2.join(df20_1)
data_2020

{'EARNINGS': '$7,344,040', 'CUP': '2570', 'EVNTS': '18', 'RNDS': '66', 'CUTS': '15', 'TOP10': '10', 'WINS': '3', 'SCORE': '68.8', 'DDIS': '304.2', 'DACC': '57.3', 'GIR': '69.6', 'PUTTS': '1.722', 'SAND': '62.5', 'BIRDS': '4.545'}

,Rank,Name,Age,EARNINGS,CUP,EVNTS,RNDS,CUTS,TOP10,WINS,SCORE,DDIS,DACC,GIR,PUTTS,SAND,BIRDS
0,1,Justin Thomas,29,"$7,344,040",2570,18,66,15,10,3,68.8,304.2,57.3,69.6,1.722,62.5,4.545
1,2,Jon Rahm,28,"$5,959,819",3080,15,58,14,8,2,68.8,307.6,63.1,70.3,1.717,58.8,4.224
2,3,Dustin Johnson,38,"$5,837,267",3471,14,49,11,7,3,68.9,311.0,59.1,69.3,1.704,54.2,4.347
3,4,Collin Morikawa,26,"$5,250,868",2025,21,80,19,7,2,69.6,297.3,65.5,69.0,1.749,54.0,4.050
4,5,Webb Simpson,37,"$5,097,742",2163,14,52,12,8,2,68.1,296.2,67.3,70.8,1.691,56.3,4.673
5,6,Bryson DeChambeau,29,"$4,998,495",1682,17,62,14,9,1,68.8,322.1,57.4,68.5,1.726,62.9,4.419
6,7,Daniel Berger,29,"$4,439,420",2007,17,64,15,7,1,68.8,300.2,63.9,66.9,1.728,59.8,4.375
7,8,Rory McIlroy,33,"$4,408,415",1516,15,60,15,7,1,69.1,314.0,56.3,67.8,1.738,45.2,4.200
8,9,Sungjae Im,24,"$4,337,811",1650,26,94,21,7,1,69.6,300.5,64.5,67.1,1.734,58.8,4.149
9,10,Patrick Reed,32,"$4,250,060",1485,20,74,17,8,1,69.4,296.0,56.1,65.3,1.700,60.6,4.230
10,11,Xander Schauffele,29,"$3,813,636",1449,18,70,17,7,0,69.0,305.4,60.3,70.9,1.737,56.4,4.243
11,12,Hideki Matsuyama,31,"$3,665,825",1587,20,74,17,5,0,69.4,304.4,57.0,68.5,1.755,55.0,4.041
12,13,Tyrrell Hatton,31,"$3,434,867",1275,11,42,10,6,1,69.1,301.6,61.7,69.3,1.704,43.2,4.548
13,14,Brendon Todd,37,"$3,390,258",1576,25,86,18,4,2,69.7,282.7,71.4,65.5,1.736,61.6,3.907
14,15,Harris English,33,"$3,299,366",1805,20,76,18,6,0,69.1,300.9,61.7,70.9,1.749,51.3,4.026
15,16,Lanto Griffin,34,"$3,188,586",1392,27,92,21,4,1,70.1,302.5,57.2,65.5,1.753,54.5,3.870
16,17,Marc Leishman,39,"$3,109,752",1096,18,61,13,3,1,71.2,295.8,51.9,61.5,1.770,42.1,3.393
17,18,Tony Finau,33,"$2,932,286",1237,20,72,16,7,0,69.4,309.8,51.8,68.8,1.730,47.7,4.194
18,19,Joaquin Niemann,24,"$2,914,136",1366,23,76,15,4,1,69.9,301.7,56.5,69.3,1.767,51.4,3.921
19,20,Abraham Ancer,32,"$2,903,306",1159,20,74,17,4,0,69.6,297.5,64.4,67.0,1.743,49.2,3.797
20,21,Sebastián Muñoz,30,"$2,864,142",1421,26,84,16,5,1,69.9,302.3,60.4,66.3,1.748,50.0,4.048
21,22,Scottie Scheffler,26,"$2,833,438",1391,23,82,18,7,0,69.3,308.9,61.2,69.0,1.737,49.0,4.354
22,23,Kevin Na,39,"$2,794,402",1102,21,71,15,4,1,70.1,286.9,62.7,63.2,1.733,55.6,3.803
23,24,Ryan Palmer,46,"$2,724,926",1116,19,68,15,5,0,70.0,299.3,60.1,65.9,1.742,50.0,3.985
24,25,Kevin Streelman,44,"$2,520,845",944,23,73,13,4,0,70.4,293.9,65.9,67.7,1.763,52.9,3.822
25,26,Billy Horschel,36,"$2,383,908",953,22,79,17,6,0,70.0,299.3,62.8,66.2,1.738,50.0,3.924
26,27,Cameron Smith,29,"$2,372,487",1059,19,64,13,2,1,70.3,299.8,54.5,64.1,1.736,57.5,3.859
27,28,Cameron Champ,27,"$2,290,839",963,20,70,15,2,1,70.4,322.0,56.4,67.7,1.775,48.2,4.043
28,29,Byeong Hun An,31,"$2,283,951",943,22,75,15,5,0,70.3,305.7,54.3,65.8,1.756,50.7,3.827
29,30,Adam Scott,42,"$2,272,434",832,10,38,9,1,1,69.7,308.1,55.5,68.1,1.740,55.1,3.789
30,31,Kevin Kisner,39,"$2,266,752",1169,21,73,15,4,0,69.8,289.2,65.2,65.4,1.743,50.9,3.795
31,32,Matthew Wolff,23,"$2,224,348",921,21,74,16,2,0,70.4,311.6,59.0,66.8,1.772,43.5,3.865
32,33,Gary Woodland,38,"$2,195,131",801,17,62,14,6,0,69.6,305.4,60.0,68.2,1.753,47.6,4.065
33,34,Adam Long,35,"$2,186,913",950,25,88,18,3,0,70.0,292.0,62.5,67.7,1.756,45.2,3.784
34,35,Joel Dahmen,35,"$2,120,973",843,22,79,18,5,0,70.2,295.4,64.6,63.9,1.747,50.7,3.684
35,36,Patrick Cantlay,30,"$2,118,336",922,12,46,11,3,0,69.6,303.1,59.4,68.4,1.723,55.4,4.152
36,37,Matt Fitzpatrick,28,"$2,109,709",887,15,54,12,5,0,70.2,294.7,64.6,66.0,1.734,47.2,3.667
37,38,Tiger Woods,47,"$2,083,038",641,7,32,0,2,1,61.8,0.0,0.0,0.0,0.000,0.0,0.000
38,39,Mackenzie Hughes,32,"$2,079,951",980,22,70,12,4,0,70.3,298.7,55.8,63.4,1.735,54.4,3.714
39,40,Danny Lee,32,"$2,043,764",777,22,69,13,3,0,70.2,302.0,57.1,65.6,1.750,53.1,4.058
40,41,Viktor Hovland,25,"$1,982,275",1009,20,74,17,3,1,69.7,299.3,63.2,68.5,1.726,45.5,3.973
41,42,Jason Day,35,"$1,943,898",666,17,53,10,5,0,70.1,299.7,55.9,64.8,1.746,65.5,3.755
42,43,Nick Taylor,34,"$1,897,539",741,18,59,11,2,1,70.3,296.6,64.2,66.9,1.757,46.3,3.559
43,44,Paul Casey,45,"$1,868,952",730,15,56,13,1,0,69.9,307.2,63.6,70.6,1.774,47.5,3.643
44,45,Tom Hoge,33,"$1,857,073",728,24,74,13,3,0,70.3,290.4,60.6,65.6,1.768,43.3,3.770
45,46,Mark Hubbard,33,"$1,840,473",792,24,86,19,3,0,69.8,290.1,62.8,66.7,1.734,47.3,3.744
46,47,Tyler Duncan,33,"$1,799,855",834,25,83,16,1,1,70.3,286.3,69.9,67.5,1.763,43.0,3.699
47,48,Brendan Steele,39,"$1,739,131",761,20,64,14,3,0,70.0,303.6,59.9,68.1,1.762,49.5,3.859
48,49,Richy Werenski,31,"$1,716,407",836,17,56,12,3,1,70.1,298.1,58.0,66.7,1.729,50.9,3.893
49,50,Adam Hadwin,35,"$1,710,808",692,17,65,15,3,0,70.1,294.0,64.5,68.3,1.755,65.0,3.646

2019 Data

In [10]:
url = "https://www.espn.com/golf/stats/player/_/season/2019/"

# Make a GET request to the URL and store the response
response = requests.get(url)

# Parse the HTML content of the page using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Find the table containing the player data
table = soup.find('table', class_='Table Table--align-right')

# Get the table headers
headers = [th.text.strip() for th in table.find_all('th')]

# Initialize a list to store the player data
player_data = []

# Loop through each row in the table (skipping the header row)
for tr in table.find_all('tr')[1:]:
    # Get the data for each column in the row
    tds = tr.find_all('td')
    # Initialize a dictionary to store the player's data
    player = {}
    # Loop through each column and add the data to the dictionary
    for i in range(len(headers)):
        player[headers[i]] = tds[i].text.strip()
    # Add the player's data to the list
    player_data.append(player)
    # Stop the loop after 250 players have been scraped
    if len(player_data) == 250:
        break

# Print the data for the first player as an example
print(player_data[0])

df19_1 = pd.DataFrame(player_data)
df19_1

# The URL of the page we want to scrape
url = "https://www.espn.com/golf/stats/player/_/season/2019/table/general/sort/amount/dir/desc/"

# Send an HTTP request to the URL
response = requests.get(url)

# Parse the HTML content of the page using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Find the table containing the player data
table = soup.find('table')

# Extract the table headers
headers = []
for th in table.find_all('th'):
    headers.append(th.text.strip())

# Extract the player data
players = []
for tr in table.find_all('tr')[1:]:
    player_data = []
    for td in tr.find_all('td'):
        player_data.append(td.text.strip())
    players.append(player_data)

df19_2 = pd.DataFrame(players)

df19_2.columns = ['Rank', 'Name', 'Age']

data_2019 = df19_2.join(df19_1)
data_2019

{'EARNINGS': '$9,684,006', 'CUP': '-13', 'EVNTS': '21', 'RNDS': '74', 'CUTS': '20', 'TOP10': '9', 'WINS': '3', 'SCORE': '69.2', 'DDIS': '309.0', 'DACC': '61.8', 'GIR': '70.0', 'PUTTS': '1.752', 'SAND': '58.4', 'BIRDS': '4.284'}

,Rank,Name,Age,EARNINGS,CUP,EVNTS,RNDS,CUTS,TOP10,WINS,SCORE,DDIS,DACC,GIR,PUTTS,SAND,BIRDS
0,1,Brooks Koepka,32,"$9,684,006",-13,21,74,20,9,3,69.2,309.0,61.8,70.0,1.752,58.4,4.284
1,2,Rory McIlroy,33,"$7,785,286",-18,19,68,17,14,3,69.0,313.5,61.8,68.5,1.701,55.3,4.485
2,3,Matt Kuchar,44,"$6,294,690",-1,22,80,20,8,2,69.6,289.5,67.4,69.4,1.748,60.8,4.013
3,4,Patrick Cantlay,30,"$6,121,488",1,21,72,18,9,1,69.2,304.7,57.3,67.2,1.721,58.0,4.403
4,5,Gary Woodland,38,"$5,690,965",-2,24,84,21,8,1,69.8,308.2,63.4,69.0,1.759,50.4,4.381
5,6,Xander Schauffele,29,"$5,609,456",-14,21,74,18,6,2,69.6,304.1,60.3,68.4,1.744,55.6,4.081
6,7,Dustin Johnson,38,"$5,534,619",10,19,70,18,7,1,69.9,312.0,55.6,67.0,1.737,63.9,4.214
7,8,Justin Thomas,29,"$5,013,084",-13,20,72,18,7,1,69.0,302.2,60.0,70.7,1.716,52.6,4.583
8,9,Jon Rahm,28,"$4,990,110",-4,20,68,18,12,1,69.4,305.6,62.5,69.0,1.736,52.8,4.353
9,10,Webb Simpson,37,"$4,690,572",-1,21,78,20,6,0,69.1,288.6,66.8,65.8,1.726,63.0,3.859
10,11,Justin Rose,42,"$4,358,849",3,17,62,16,7,1,69.9,303.2,60.1,64.8,1.710,61.7,4.065
11,12,Tony Finau,33,"$4,344,380",-7,25,84,20,6,0,69.8,309.5,56.9,67.5,1.756,49.4,3.905
12,13,Paul Casey,45,"$4,257,040",-9,22,75,18,7,1,69.7,298.4,67.7,71.0,1.748,43.7,3.867
13,14,Adam Scott,42,"$4,084,541",-8,18,61,14,9,0,69.7,299.3,59.9,68.9,1.746,55.4,4.279
14,15,Rickie Fowler,34,"$3,945,810",0,20,76,18,6,1,69.8,303.1,60.6,67.8,1.726,54.8,4.039
15,16,Marc Leishman,39,"$3,886,577",2,21,72,17,7,1,70.0,296.2,59.4,67.2,1.755,58.2,3.889
16,17,Tommy Fleetwood,32,"$3,853,651",-1,18,64,18,6,0,69.9,298.7,64.0,66.9,1.782,63.5,3.531
17,18,Chez Reavie,41,"$3,660,909",-6,28,92,22,6,1,69.8,287.0,75.7,67.9,1.737,48.9,4.011
18,19,Patrick Reed,32,"$3,593,844",-5,25,88,22,5,1,69.8,296.8,60.1,66.2,1.731,58.8,3.977
19,20,Shane Lowry,35,"$3,490,098",1197,14,41,9,4,1,70.5,0.0,0.0,0.0,0.000,0.0,0.000
20,21,Kevin Kisner,39,"$3,489,144",-5,25,86,22,5,1,70.0,286.4,69.4,67.0,1.760,45.8,3.674
21,22,Francesco Molinari,40,"$3,467,143",1080,15,54,14,3,1,71.1,288.7,66.4,63.6,1.786,65.3,3.204
22,23,Hideki Matsuyama,31,"$3,335,137",-5,24,88,22,7,0,69.5,303.0,61.3,69.4,1.753,53.7,4.295
23,24,Tiger Woods,47,"$3,199,615",1069,12,41,0,4,1,63.4,0.0,0.0,0.0,0.000,0.0,0.000
24,25,Bryson DeChambeau,29,"$3,186,232",-4,21,72,17,5,1,69.8,302.5,65.0,66.2,1.733,52.3,4.167
25,26,Brandt Snedeker,42,"$3,122,936",2,27,99,24,6,0,70.2,287.2,63.2,64.9,1.746,62.3,3.737
26,27,Charles Howell III,43,"$3,039,049",4,27,91,21,5,1,69.7,302.8,62.8,70.5,1.763,47.5,3.846
27,28,Corey Conners,31,"$2,919,864",3,28,86,16,4,1,70.2,297.3,66.9,73.1,1.790,51.8,3.791
28,29,Ryan Palmer,46,"$2,873,316",1141,21,66,15,6,1,70.0,298.6,60.7,68.4,1.754,42.7,4.212
29,30,Sungjae Im,24,"$2,851,134",0,35,118,26,7,0,69.6,295.9,65.5,67.6,1.736,48.9,4.068
30,31,Sung Kang,35,"$2,801,650",1003,27,84,17,4,1,70.7,300.5,60.7,66.1,1.777,57.7,3.655
31,32,Abraham Ancer,32,"$2,688,625",1,27,88,20,4,0,70.0,293.3,70.2,66.8,1.749,46.6,3.886
32,33,Scott Piercy,44,"$2,679,915",1104,24,86,21,6,0,69.5,292.4,67.6,70.1,1.748,50.4,4.012
33,34,Jim Furyk,52,"$2,669,938",911,21,68,16,3,0,70.1,275.0,74.4,69.3,1.785,53.4,3.456
34,35,Jason Day,35,"$2,637,480",891,21,64,15,6,0,70.0,302.0,61.8,69.7,1.747,52.4,4.000
35,36,Lucas Glover,43,"$2,613,965",10,26,90,21,7,0,69.7,296.1,66.1,68.1,1.762,59.1,3.956
36,37,Louis Oosthuizen,40,"$2,539,183",1,19,64,16,5,0,70.2,296.3,66.9,66.8,1.751,58.1,3.922
37,38,J.T. Poston,29,"$2,461,215",1238,29,96,21,3,1,70.0,293.8,62.9,66.8,1.743,52.8,3.906
38,39,Phil Mickelson,52,"$2,440,221",948,20,60,0,2,1,71.1,306.3,50.8,64.2,1.756,55.1,3.917
39,40,Andrew Putnam,34,"$2,439,137",1145,23,76,18,3,0,70.3,281.5,60.6,65.9,1.701,61.0,4.158
40,41,Keith Mitchell,31,"$2,405,360",926,26,83,17,3,1,70.4,303.2,60.4,67.3,1.774,50.7,3.880
41,42,Rory Sabbatini,46,"$2,382,298",1140,26,93,22,6,0,69.8,289.4,66.9,66.9,1.738,55.6,4.032
42,43,C.T. Pan,31,"$2,362,399",1125,25,82,17,2,1,70.6,285.0,64.8,64.2,1.765,57.4,3.488
43,44,Jason Kokrak,37,"$2,330,212",-3,24,90,23,5,0,70.0,306.4,62.7,68.8,1.761,47.5,4.044
44,45,Kevin Tway,34,"$2,300,050",1242,26,80,16,2,1,70.4,303.8,55.3,67.0,1.780,50.0,3.563
45,46,Kevin Na,39,"$2,257,309",823,19,60,14,3,1,70.9,289.6,64.0,64.4,1.767,55.3,3.417
46,47,Si Woo Kim,27,"$2,191,808",956,28,82,16,5,0,70.2,292.4,62.9,64.9,1.729,56.6,4.122
47,48,Billy Horschel,36,"$2,187,249",1065,26,92,24,4,0,70.3,291.8,64.7,67.6,1.762,47.9,3.609
48,49,Ian Poulter,47,"$2,162,306",1072,18,58,15,6,0,70.3,291.5,63.6,66.9,1.736,62.0,4.103
49,50,J.B. Holmes,40,"$2,147,065",856,25,71,15,2,1,71.2,306.7,56.5,65.6,1.786,53.1,3.761

2018 Data

In [11]:
url = "https://www.espn.com/golf/stats/player/_/season/2018/"

# Make a GET request to the URL and store the response
response = requests.get(url)

# Parse the HTML content of the page using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Find the table containing the player data
table = soup.find('table', class_='Table Table--align-right')

# Get the table headers
headers = [th.text.strip() for th in table.find_all('th')]

# Initialize a list to store the player data
player_data = []

# Loop through each row in the table (skipping the header row)
for tr in table.find_all('tr')[1:]:
    # Get the data for each column in the row
    tds = tr.find_all('td')
    # Initialize a dictionary to store the player's data
    player = {}
    # Loop through each column and add the data to the dictionary
    for i in range(len(headers)):
        player[headers[i]] = tds[i].text.strip()
    # Add the player's data to the list
    player_data.append(player)
    # Stop the loop after 250 players have been scraped
    if len(player_data) == 250:
        break

# Print the data for the first player as an example
print(player_data[0])

df18_1 = pd.DataFrame(player_data)
df18_1

# The URL of the page we want to scrape
url = "https://www.espn.com/golf/stats/player/_/season/2018/table/general/sort/amount/dir/desc/"

# Send an HTTP request to the URL
response = requests.get(url)

# Parse the HTML content of the page using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Find the table containing the player data
table = soup.find('table')

# Extract the table headers
headers = []
for th in table.find_all('th'):
    headers.append(th.text.strip())

# Extract the player data
players = []
for tr in table.find_all('tr')[1:]:
    player_data = []
    for td in tr.find_all('td'):
        player_data.append(td.text.strip())
    players.append(player_data)

df18_2 = pd.DataFrame(players)

df18_2.columns = ['Rank', 'Name', 'Age']

data_2018 = df18_2.join(df18_1)
data_2018

{'EARNINGS': '$8,694,821', 'CUP': '1610', 'EVNTS': '23', 'RNDS': '82', 'CUTS': '21', 'TOP10': '10', 'WINS': '3', 'SCORE': '69.1', 'DDIS': '311.8', 'DACC': '58.4', 'GIR': '68.8', 'PUTTS': '1.714', 'SAND': '54.3', 'BIRDS': '4.341'}

,Rank,Name,Age,EARNINGS,CUP,EVNTS,RNDS,CUTS,TOP10,WINS,SCORE,DDIS,DACC,GIR,PUTTS,SAND,BIRDS
0,1,Justin Thomas,29,"$8,694,821",1610,23,82,21,10,3,69.1,311.8,58.4,68.8,1.714,54.3,4.341
1,2,Dustin Johnson,38,"$8,457,352",2056,20,74,19,12,3,68.5,314.0,59.5,70.6,1.699,52.2,4.703
2,3,Justin Rose,42,"$8,130,678",2260,18,66,17,11,2,69.0,303.5,66.0,69.9,1.732,61.2,4.530
3,4,Bryson DeChambeau,29,"$8,094,489",2188,26,93,22,9,3,69.6,305.7,62.2,69.7,1.758,48.7,4.204
4,5,Brooks Koepka,32,"$7,094,047",1093,17,62,16,6,2,69.4,313.4,56.8,68.3,1.747,53.8,4.194
5,6,Bubba Watson,44,"$5,793,748",918,24,79,19,6,3,70.1,313.1,58.3,68.2,1.773,44.2,3.747
6,7,Tony Finau,33,"$5,620,138",1732,28,98,25,11,0,69.5,315.1,55.1,70.2,1.735,44.4,4.133
7,8,Tiger Woods,47,"$5,443,841",2219,18,68,16,7,1,69.6,303.6,59.3,67.4,1.744,48.1,4.029
8,9,Webb Simpson,37,"$5,376,417",844,26,92,23,9,1,69.3,293.7,62.3,67.9,1.741,62.9,3.587
9,10,Jason Day,35,"$5,087,461",564,20,68,18,5,2,69.7,310.0,58.3,65.3,1.716,62.5,4.176
10,11,Francesco Molinari,40,"$5,065,842",512,20,70,17,5,2,69.9,301.0,65.0,70.2,1.780,47.9,3.771
11,12,Patrick Reed,32,"$5,006,267",438,26,86,20,7,1,70.2,298.1,55.1,63.6,1.746,56.7,3.756
12,13,Phil Mickelson,52,"$4,595,187",448,24,87,21,6,1,70.1,300.3,52.9,64.9,1.699,58.6,4.310
13,14,Rory McIlroy,33,"$4,410,296",602,18,61,14,7,1,69.5,319.7,55.8,66.3,1.736,52.4,4.000
14,15,Billy Horschel,36,"$4,315,200",1840,27,82,17,6,1,69.8,295.4,67.8,71.7,1.757,51.7,3.915
15,16,Rickie Fowler,34,"$4,235,237",512,20,74,17,6,0,69.4,299.8,65.3,69.5,1.744,60.5,4.000
16,17,Keegan Bradley,36,"$4,069,464",1253,27,93,23,5,1,70.2,299.6,67.9,69.2,1.784,45.2,3.645
17,18,Xander Schauffele,29,"$4,047,538",581,27,93,22,7,0,70.4,304.9,59.8,65.6,1.763,48.4,3.806
18,19,Jon Rahm,28,"$3,992,678",422,20,66,16,5,1,69.7,308.9,59.2,70.1,1.747,48.5,4.439
19,20,Patrick Cantlay,30,"$3,963,962",453,23,80,21,7,1,69.9,303.1,61.6,70.7,1.781,53.9,3.825
20,21,Tommy Fleetwood,32,"$3,935,147",483,19,66,18,6,0,69.5,306.9,65.0,69.4,1.745,51.7,4.318
21,22,Kyle Stanley,35,"$3,916,001",373,26,88,20,5,0,70.3,295.7,71.3,71.1,1.781,46.2,3.818
22,23,Marc Leishman,39,"$3,771,221",284,25,90,22,6,0,70.1,298.5,60.2,66.7,1.749,48.8,3.956
23,24,Paul Casey,45,"$3,641,771",403,20,71,17,5,1,70.0,304.3,63.1,67.8,1.775,54.5,3.775
24,25,Cameron Smith,29,"$3,622,607",660,24,78,18,7,0,70.4,298.4,57.0,63.2,1.745,56.5,3.692
25,26,Kevin Na,39,"$3,578,316",336,26,86,20,4,1,69.9,289.6,64.1,64.7,1.722,61.5,3.907
26,27,Patton Kizzire,37,"$3,541,151",275,29,89,18,4,2,70.4,298.7,55.6,69.0,1.764,46.8,3.775
27,28,Aaron Wise,26,"$3,486,407",418,29,88,16,4,1,70.1,302.9,63.3,68.8,1.748,47.9,4.114
28,29,Gary Woodland,38,"$3,108,907",385,27,91,21,3,1,70.2,313.5,63.7,70.5,1.794,41.5,3.802
29,30,Kevin Kisner,39,"$2,972,285",1132,25,78,18,4,0,70.4,290.8,66.3,65.4,1.766,44.0,3.436
30,31,Pat Perez,47,"$2,962,641",1190,23,75,19,4,1,70.6,290.9,65.1,67.8,1.765,47.2,3.853
31,32,Jordan Spieth,29,"$2,793,536",1323,23,76,18,5,0,69.5,299.8,61.6,70.5,1.755,51.3,4.158
32,33,Chesson Hadley,35,"$2,768,863",1163,30,99,23,7,0,70.1,300.0,60.1,67.7,1.740,46.1,3.939
33,34,Brian Harman,36,"$2,733,463",1129,25,90,22,8,0,70.5,291.9,67.1,67.6,1.767,47.2,3.733
34,35,Ian Poulter,47,"$2,714,450",1090,20,64,16,4,1,70.6,293.6,66.4,67.0,1.766,50.4,3.750
35,36,Luke List,38,"$2,710,736",1150,29,95,20,5,0,70.3,314.6,54.7,68.4,1.794,52.2,3.863
36,37,Chez Reavie,41,"$2,700,018",1252,28,86,19,3,0,70.2,286.5,72.2,68.7,1.767,43.1,3.709
37,38,Alex Noren,40,"$2,699,150",1169,18,60,14,3,0,70.4,299.2,61.7,64.9,1.782,51.9,3.467
38,39,Hideki Matsuyama,31,"$2,687,477",602,21,72,19,4,0,69.8,302.0,62.8,69.3,1.754,52.0,3.944
39,40,Henrik Stenson,46,"$2,680,487",990,16,56,14,5,0,69.7,291.5,75.2,73.5,1.800,55.6,3.643
40,41,Andrew Landry,35,"$2,642,179",1225,27,80,15,5,1,70.7,291.1,62.9,65.6,1.756,42.6,3.500
41,42,Byeong Hun An,31,"$2,599,264",1170,24,84,19,4,0,70.3,307.9,60.2,68.0,1.791,48.9,3.655
42,43,Emiliano Grillo,30,"$2,493,163",1270,25,92,22,6,0,70.0,295.2,70.2,68.8,1.754,54.8,3.891
43,44,Ryan Armour,47,"$2,485,203",1113,32,107,22,3,1,70.2,283.5,73.6,68.2,1.773,52.5,3.664
44,45,Rafa Cabrera Bello,38,"$2,449,869",1175,20,70,18,5,0,70.0,295.1,67.9,70.2,1.773,56.9,3.771
45,46,Beau Hossler,27,"$2,449,707",1134,28,104,24,5,0,70.2,300.0,60.5,67.9,1.748,54.2,3.788
46,47,Brandt Snedeker,42,"$2,448,970",1188,25,82,17,4,1,70.2,293.1,62.8,65.0,1.743,56.7,3.622
47,48,Austin Cook,32,"$2,448,920",1203,29,107,24,3,1,70.1,292.3,66.8,66.5,1.756,53.4,3.916
48,49,Andrew Putnam,34,"$2,387,382",1267,28,89,21,5,1,70.1,293.8,60.4,70.5,1.783,48.8,3.629
49,50,Brendan Steele,39,"$2,291,128",1015,22,67,16,3,1,71.0,310.3,60.5,69.2,1.817,48.0,3.478

Combining the Datasets

In [12]:
dfGolf = pd.concat([data_2022, data_2021, data_2020, data_2019, data_2018], ignore_index=True,axis=0)
dfGolf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 17 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Rank      250 non-null    object
 1   Name      250 non-null    object
 2   Age       250 non-null    object
 3   EARNINGS  250 non-null    object
 4   CUP       250 non-null    object
 5   EVNTS     250 non-null    object
 6   RNDS      250 non-null    object
 7   CUTS      250 non-null    object
 8   TOP10     250 non-null    object
 9   WINS      250 non-null    object
 10  SCORE     250 non-null    object
 11  DDIS      250 non-null    object
 12  DACC      250 non-null    object
 13  GIR       250 non-null    object
 14  PUTTS     250 non-null    object
 15  SAND      250 non-null    object
 16  BIRDS     250 non-null    object
dtypes: object(17)
memory usage: 33.3+ KB

Dropping Columns

In [13]:
dfGolf

,Rank,Name,Age,EARNINGS,CUP,EVNTS,RNDS,CUTS,TOP10,WINS,SCORE,DDIS,DACC,GIR,PUTTS,SAND,BIRDS
0,1,Scottie Scheffler,26,"$14,046,910",-20,25,84,20,11,4,68.9,311.6,60.0,72.3,1.720,49.5,4.595
1,2,Cameron Smith,29,"$10,107,897",-9,18,62,14,7,3,68.9,299.7,57.5,68.0,1.679,52.2,4.629
2,3,Will Zalatoris,26,"$9,405,082",3680,24,76,17,9,1,69.6,314.7,55.4,70.9,1.734,49.0,4.316
3,4,Patrick Cantlay,30,"$9,369,605",-16,20,68,17,12,2,69.0,308.0,60.6,69.3,1.732,57.7,4.441
4,5,Rory McIlroy,33,"$8,654,566",-21,16,60,14,10,3,68.9,321.3,58.1,69.9,1.739,61.6,4.533
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,46,Beau Hossler,27,"$2,449,707",1134,28,104,24,5,0,70.2,300.0,60.5,67.9,1.748,54.2,3.788
246,47,Brandt Snedeker,42,"$2,448,970",1188,25,82,17,4,1,70.2,293.1,62.8,65.0,1.743,56.7,3.622
247,48,Austin Cook,32,"$2,448,920",1203,29,107,24,3,1,70.1,292.3,66.8,66.5,1.756,53.4,3.916
248,49,Andrew Putnam,34,"$2,387,382",1267,28,89,21,5,1,70.1,293.8,60.4,70.5,1.783,48.8,3.629
249,50,Brendan Steele,39,"$2,291,128",1015,22,67,16,3,1,71.0,310.3,60.5,69.2,1.817,48.0,3.478

In [14]:
dfGolf2 = dfGolf.drop(columns = ['Name', 'Rank', 'CUP', 'Age', 'EVNTS'])
dfGolf2['EARNINGS'] = dfGolf2['EARNINGS'].str.replace('$','')
dfGolf2['EARNINGS'] = dfGolf2['EARNINGS'].str.replace(',','')
dfGolf2

C:\Users\camer\AppData\Local\Temp\ipykernel_22444\274302120.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  dfGolf2['EARNINGS'] = dfGolf2['EARNINGS'].str.replace('$','')

,EARNINGS,RNDS,CUTS,TOP10,WINS,SCORE,DDIS,DACC,GIR,PUTTS,SAND,BIRDS
0,14046910,84,20,11,4,68.9,311.6,60.0,72.3,1.720,49.5,4.595
1,10107897,62,14,7,3,68.9,299.7,57.5,68.0,1.679,52.2,4.629
2,9405082,76,17,9,1,69.6,314.7,55.4,70.9,1.734,49.0,4.316
3,9369605,68,17,12,2,69.0,308.0,60.6,69.3,1.732,57.7,4.441
4,8654566,60,14,10,3,68.9,321.3,58.1,69.9,1.739,61.6,4.533
...,...,...,...,...,...,...,...,...,...,...,...,...
245,2449707,104,24,5,0,70.2,300.0,60.5,67.9,1.748,54.2,3.788
246,2448970,82,17,4,1,70.2,293.1,62.8,65.0,1.743,56.7,3.622
247,2448920,107,24,3,1,70.1,292.3,66.8,66.5,1.756,53.4,3.916
248,2387382,89,21,5,1,70.1,293.8,60.4,70.5,1.783,48.8,3.629
249,2291128,67,16,3,1,71.0,310.3,60.5,69.2,1.817,48.0,3.478

In [15]:
dfGolf3 = dfGolf2.astype({"EARNINGS": int, "RNDS": int, "CUTS":int, "TOP10": int, "WINS": int, "SCORE": float, "DDIS": float, "DACC": float, "GIR": float, 
                          "PUTTS": float, "SAND": float, "BIRDS": float})
dfGolf3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   EARNINGS  250 non-null    int32
 1   RNDS      250 non-null    int32
 2   CUTS      250 non-null    int32
 3   TOP10     250 non-null    int32
 4   WINS      250 non-null    int32
 5   SCORE     250 non-null    float64
 6   DDIS      250 non-null    float64
 7   DACC      250 non-null    float64
 8   GIR       250 non-null    float64
 9   PUTTS     250 non-null    float64
 10  SAND      250 non-null    float64
 11  BIRDS     250 non-null    float64
dtypes: float64(7), int32(5)
memory usage: 18.7 KB

In [16]:
dfGolf4 = dfGolf3.sort_values(by=['EARNINGS'], ascending=False)
dfGolf5 = dfGolf4.reset_index()

In [17]:
dfGolf6 = dfGolf5.drop(columns= ['index'])
dfGolf6

,EARNINGS,RNDS,CUTS,TOP10,WINS,SCORE,DDIS,DACC,GIR,PUTTS,SAND,BIRDS
0,14046910,84,20,11,4,68.9,311.6,60.0,72.3,1.720,49.5,4.595
1,10107897,62,14,7,3,68.9,299.7,57.5,68.0,1.679,52.2,4.629
2,9684006,74,20,9,3,69.2,309.0,61.8,70.0,1.752,58.4,4.284
3,9405082,76,17,9,1,69.6,314.7,55.4,70.9,1.734,49.0,4.316
4,9369605,68,17,12,2,69.0,308.0,60.6,69.3,1.732,57.7,4.441
...,...,...,...,...,...,...,...,...,...,...,...,...
245,1840473,86,19,3,0,69.8,290.1,62.8,66.7,1.734,47.3,3.744
246,1799855,83,16,1,1,70.3,286.3,69.9,67.5,1.763,43.0,3.699
247,1739131,64,14,3,0,70.0,303.6,59.9,68.1,1.762,49.5,3.859
248,1716407,56,12,3,1,70.1,298.1,58.0,66.7,1.729,50.9,3.893
249,1710808,65,15,3,0,70.1,294.0,64.5,68.3,1.755,65.0,3.646

In [18]:
list(dfGolf6.columns)

['EARNINGS',
 'RNDS',
 'CUTS',
 'TOP10',
 'WINS',
 'SCORE',
 'DDIS',
 'DACC',
 'GIR',
 'PUTTS',
 'SAND',
 'BIRDS']

In [19]:
dict = {'EARNINGS':'Earnings for Year',
 'RNDS':'Rounds Played',
 'CUTS':'Cuts Made',
 'TOP10': 'Top 10 Finishes',
 'WINS':'Wins',
 'SCORE':'Average Score',
 'DDIS': 'Average Driving Distance',
 'DACC':'Driving Accuracy Percentage',
 'GIR':'Greens in Regulation Percentage',
 'PUTTS':'Putts Per Hole',
 'SAND':'Save Percentage',
 'BIRDS':'Birdies Per Round'}

In [20]:
dfGolf6.rename(columns=dict, inplace=True)
dfGolf6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 12 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Earnings for Year                250 non-null    int32
 1   Rounds Played                    250 non-null    int32
 2   Cuts Made                        250 non-null    int32
 3   Top 10 Finishes                  250 non-null    int32
 4   Wins                             250 non-null    int32
 5   Average Score                    250 non-null    float64
 6   Average Driving Distance         250 non-null    float64
 7   Driving Accuracy Percentage      250 non-null    float64
 8   Greens in Regulation Percentage  250 non-null    float64
 9   Putts Per Hole                   250 non-null    float64
 10  Save Percentage                  250 non-null    float64
 11  Birdies Per Round                250 non-null    float64
dtypes: float64(7), int32(5)
memory usage: 18.7 KB

FINAL DATAFRAME

In [21]:
df = dfGolf6
df

,Earnings for Year,Rounds Played,Cuts Made,Top 10 Finishes,Wins,Average Score,Average Driving Distance,Driving Accuracy Percentage,Greens in Regulation Percentage,Putts Per Hole,Save Percentage,Birdies Per Round
0,14046910,84,20,11,4,68.9,311.6,60.0,72.3,1.720,49.5,4.595
1,10107897,62,14,7,3,68.9,299.7,57.5,68.0,1.679,52.2,4.629
2,9684006,74,20,9,3,69.2,309.0,61.8,70.0,1.752,58.4,4.284
3,9405082,76,17,9,1,69.6,314.7,55.4,70.9,1.734,49.0,4.316
4,9369605,68,17,12,2,69.0,308.0,60.6,69.3,1.732,57.7,4.441
...,...,...,...,...,...,...,...,...,...,...,...,...
245,1840473,86,19,3,0,69.8,290.1,62.8,66.7,1.734,47.3,3.744
246,1799855,83,16,1,1,70.3,286.3,69.9,67.5,1.763,43.0,3.699
247,1739131,64,14,3,0,70.0,303.6,59.9,68.1,1.762,49.5,3.859
248,1716407,56,12,3,1,70.1,298.1,58.0,66.7,1.729,50.9,3.893
249,1710808,65,15,3,0,70.1,294.0,64.5,68.3,1.755,65.0,3.646

In [24]:
df.to_csv('GolfEarnings.csv', index=False)